### ISSUE TITLE
Events not emitted from "wrapper" elements

### ISSUE THREAD

**Issue by kaosat-dev** [pH200/cycle-react#12]
Hi, 
It seems I have run into a bit of a problem with events (click, drag etc) from "wrapper" elements not "firing"

ie for a simple element like this : 
```
<div className="wrapperDiv">
  Hi there sub !
  <div className="innerDiv">
    some sub div
    </div>
</div>
```

```interactions.get(".wrapperDiv","click")  ```
will never "emit" anything

while 
```interactions.get(".innerDiv","click")  ```
will work as expected 

more extensive example of the issue here : 
http://codepen.io/anon/pen/LVeVOg?editors=001

This issue is not specific to any event type, btw .
Am I missing something regarding how event handling and "injection" into interactions works ?

Thanks again for the great work, other than this one, no issues so far :)

**Comment by pH200** [comment]
Hi, thanks for the report.

We have this issue because React will render the element form:

```js
<div className="wrapperDiv">
  Hi there sub !
  <div className="innerDiv">
    some sub div
  </div>
</div>
```

Into:

```js
<div className="wrapperDiv">
  <span>Hi there sub !</span>
  <div className="innerDiv">
    some sub div
  </div>
</div>
```

And `interactions.get` is listening the events from elements by using [e.target.matches(className)](https://developer.mozilla.org/en/docs/Web/API/Element/matches). Therefore, the event will not emit because it's coming from the span not the wrapperDiv.

Also, it's very important to notice that Cycle-React will remove the current `interactions.get()` API and switch into event handlers for the next (1.0) version. So, this issue will no longer exist since Cycle-React will be using the [event system](https://facebook.github.io/react/docs/events.html) from React. Details can be found at #8. I made this decision because I think it's better to have a single interactions API for both Cycle-React components and other React components that use event handlers.

**Comment by kaosat-dev** [comment]
Thanks a lot for the explanation and very fast reply ! 
That does make the issue clearer !
Does that mean that in the future , events will either need to use refs or getEventSubject (with the "emit" variant of #8 ?) 
The main advantage I found with selectors (and to an extent, refs) vs inline handlers, is the more concise way of handling multiple events for the same element:
ie, dragover/drop etc or  touch/mouseDown combos etc

**Comment by pH200** [comment]
> Does that mean that in the future , events will either need to use refs or getEventSubject (with the "emit" variant of #8 ?) 

Yes. And `getEventSubject` will be renamed to `get`, the current `get` will be removed. Refs are not needed for using events. And I think you'll lose the support of React's event system by using the element's event handlers through refs.

Selector API creates a coupling between View and Intentions by using `className` and `selector`. On the other hand, the event handler API also has the same coupling by matching the name of event handlers. They have different [concepts](https://github.com/cyclejs/cycle-core/blob/master/docs/faq.md#i-dont-like-to-use-classname-based-selectors-reminds-me-of-jquery), but I think event handler API works as well as selector API in terms of coding.

> Btw are there any other similar "gotchas/changes" planned for v1.0 ?

- Interactions API will change #8
- Virtual-hyperscript helper will be removed because we've already got JSX #11

That's probably everything for 1.0. And 1.0 will be our stable version :)

**Comment by kaosat-dev** [comment]
Ok great, thanks !

>And I think you'll lose the support of React's event system by using the element's event handlers through refs

I mostly use refs for external libraries like three.js which can only work by "injecting" special canvas elements in the dom, so not too much worries with events there so far :)

>They have different concepts, but I think event handler API works as well as selector API in terms of coding

yeah you cannot escape some amount of coupling, so I guess it is a matter of taste in the end , I am currently doing back & forths between the React style event handlers and Cycle's selector, not too sure about how either will scale.

> That's probably everything for 1.0. And 1.0 will be our stable version :)
Great ! :+1:  Thanks a lot for the infos :)

**Comment by pH200** [comment]
Fixed and [tested](https://github.com/pH200/cycle-react/blob/cr1.0.1/test/browser/render.js#L111-L133)

Migration guide can be found at the [changelog](https://github.com/pH200/cycle-react/blob/master/CHANGELOG.md#101)
