### ISSUE TITLE
Why is there no lifecycle event for componenDidUpdate?

### ISSUE THREAD

**Issue by agenthunt** [pH200/cycle-react#18]
Is there any specific reason, there is no lifecycle event for componenDidUpdate? I have a usecase where I need to find something in the dom after the component has updated ? Any suggestions on how to go about this ?

**Comment by pH200** [comment]
We do really need a lifecycle event for `componentDidMount`. However, it might not be that necessary to have a lifecycle event for `componentDidUpdate`. Because:

1. You can hook up events in `componentDidUpdate` for such use cases
2. There is no componentDidUpdate hook in [virtual-dom](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md)

Having said that, we still need a lifecycle event for `componentDidMount`. And it's probably fine having other lifecycle events such as `componentDidUpdate` as well. I am going to make updates. The API is going to look like this:

```
const Foo = component('Foo', function (interactions) {
  const componentDidUpdate$ = interactions.get('React_componentDidUpdate')
    .map(refs => {
      const inputElement = React.findDOMNode(refs.refInput);
      // manipulate DOM elements
    });

  return Rx.Observable.just('')
    .merge(componentDidUpdate$)
    .map(value => <input type="text" ref="refInput" />);
}):
```

**Comment by pH200** [comment]
Sorry it took me a long time to look back at this issue. We have now supported the component's lifecycles by introducing a new parameter for the component's definition function. Details can be found at [Working with React](/docs/working-with-react.md#lifecycle-events)

I'm now closing this issue. Feel free to reopen this if you have any questions. Thanks.
