### ISSUE TITLE
[very minor] consider renaming to recycle.js

### ISSUE THREAD

**Issue by sunny-g** [pH200/cycle-react#33]
A friend and I were talking about this project and he mentioned that to improve its Google-ability, cycle-react could be renamed as `recycle.js` as it is not only an amalgam of React and Cycle but also represents the recycling of ideas from both.

Although `recycle` is taken on NPM as [recycle](https://www.npmjs.com/package/recycle), the project doesn't exist anymore on Github, hence the name `recycle.js`. 

Any thoughts @pH200? Also, if it wasn't clear, this project is awesome and way more approachable and usable to me than Cycle.js, so thank you for writing it!

**Comment by ryanhiebert** [comment]
I don't think you can ask for much better google-ability for an amalgamation of cycle and react than `cycle-react`. If I search for "use react with cycle", it's the first thing that comes up. "recycle" may be a more clever name, but it's certainly not more googlable, especially if you don't already know what you're looking for.

**Comment by sunny-g** [comment]
@ryanhiebert well I brought this up partially because I find way more resources about using Cycle.js with React than anything specific to this project, not to mention that Googling "cycle-react-native" only brings up the link to this repo and everything else is about Cycle.js and React Native. 

I can also imagine that if this project were to become the de facto way for integrating Rx and React (in the Cycle way of course), searching "cycle react" will only get more lost in the Cycle.js + React search results, whereas nothing relevant comes up when searching "recycle js" at the moment, and if you were to search "recycle react", you would definitely end up here.

Anyways, I'm not wedded to this at all, just wanted to start discussion. Thanks for your input!

**Comment by corps** [comment]
I think the issue is that, frankly, there aren't many blog posts or examples to find, even with more google-able terms.

That said... honestly, cycle-react is only, like, 300 lines of code?  It's fairly easy to dig into.
To cycle react, you basically just need to know how to use

1.  React

and

2.  RxJS

Fortunately you can google tons of examples for each of those separately.  Cycle-react to me is really less about being Cycle.js and more about being Rx.JS + React, and I like it that way.  There's not very much to say about cycle-react itself.

**Comment by pH200** [comment]
@sunny-g I understand. We really need a solid introduction of how to use Cycle-React in the real world as you said. I don't like to change the name right now, but examples and blog posts as well as the projects in production are the missing parts without any question.
