### ISSUE TITLE
Apparent react-router incompatibility

### ISSUE THREAD

**Issue by talexand** [pH200/cycle-react#35]
Re: https://github.com/pH200/cycle-react/issues/13, I could sorely do with a routing example.

Since cycle-react uses React to render, I figured I was limited to routers that specifically had React in mind. Specifically, I was looking for something that offered the usual nesting with `children` at each route component.

[A minimal example](https://gist.github.com/talexand/bf6cf172d5bcb1962f788b3dbe47d258) with `react`, `react-router`, and `cycle-react` resulted in a strange rendering of the route string:

![bad render](http://imgur.com/Le3mosV.jpg)

Is there a bug here, or am I just doing it wrong?

**Comment by pH200** [comment]
Sorry to say that but you're probably doing it wrong. You want the `children` from `props`. But, `props.get` will actually get you an `Observable` of that property. You need to combine that Observable into your view Observable to use it in JSX correctly.

```js
// Wrong
return Observable.just(<div>props.get('foo')</div>);
```
```js
// Do either this:
return props.get('foo').map(foo => <div>{foo}</div>);
// Or this:
return props.map(({foo}) => <div>{foo}</div>);
```

Here's the fix for your example:
https://gist.github.com/pH200/5e006b550f159a3af89d6d3f0d5cd8fd

Finally, I'll keep in mind that I need to write an example for react-router, too.

**Comment by talexand** [comment]
Thank you for that; I see what I was getting wrong. The gist you posted is already a pretty good example.
